[package]
name = "vm"
version = "0.1.0"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]
edition = "2018"

[dependencies]
error = { path = "../common/error" }
logger = { path = "../common/logger" }
anyhow = "1.0.38"
crypto = { path = "../crypto"}
movelang = { path = "../movelang"}
bellman = { package = "bellman_ce", version = "0.3.0" }
ff = { package = "ff_ce", version = "0.6.0", features = ["derive"] }
num-bigint = "0.2.3"
num-traits = "0.2.8"
rand = "0.4.6"
move-binary-format = { git = "https://github.com/zkmove/diem", rev ="0e608052d180d5ef7e3c4a5884cbd26e5e8d1be6" }
move-vm-runtime = { git = "https://github.com/zkmove/diem", rev ="0e608052d180d5ef7e3c4a5884cbd26e5e8d1be6" }
move-core-types = { git = "https://github.com/zkmove/diem", rev ="0e608052d180d5ef7e3c4a5884cbd26e5e8d1be6" }
halo2 = { git = "https://github.com/guangyuz/halo2", rev = "0dd737a7bd331011c42df8ef4f953b55426768a0" }

[dev-dependencies]
datatest-stable = "0.1.1"

#[[test]]
#name = "scripts"
#harness = false

[[test]]
name = "testsuite"
harness = false