[package]
name = "vm"
version = "0.1.0"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]
edition = "2018"

[dependencies]
logger = { path = "../common/logger" }
anyhow = "1.0.38"
crypto = { path = "../crypto"}
movelang = { path = "../movelang"}
bellman = { package = "bellman_ce", version = "0.3.0" }
ff = { package = "ff_ce", version = "0.6.0", features = ["derive"] }
num-bigint = "0.2.3"
num-traits = "0.2.8"
move-binary-format = { git = "https://github.com/zkmove/diem", rev ="85588fbcff7246d0d47daea7bae861a3b36bdb6b" }
move-vm-runtime = { git = "https://github.com/zkmove/diem", rev ="85588fbcff7246d0d47daea7bae861a3b36bdb6b" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "testsuite"
harness = false