[package]
name = "zkmove-cli"
version = "0.1.0"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]
edition = "2018"

[dependencies]
error = { path = "../common/error" }
functional-tests = { path = "../functional-tests" }
logger = { path = "../common/logger" }
movelang = { path = "../movelang" }
structopt = "0.3.25"
vm = { path = "../vm" }
halo2_proofs = { git = "https://github.com/young-rocks/halo2", rev = "e5c022414e62154b66b9fbef463912768c15556a" }

[dev-dependencies]

[[bin]]
name = "zkmove"
path = "src/main.rs"