[package]
name = "movelang"
version = "0.1.0"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
log = "0.4.14"
move-lang = { git = "https://github.com/diem/diem", branch="release-1.3" }
move-binary-format = { git = "https://github.com/diem/diem", branch="release-1.3" }