[package]
name = "movelang"
version = "0.1.0"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]
edition = "2018"

[dependencies]
move-compiler = { git = "https://github.com/young-rocks/move", rev = "4e8d09188f056bf7a5daba4095c6c9bdcc51b74f" }
move-binary-format = { git = "https://github.com/young-rocks/move", rev = "4e8d09188f056bf7a5daba4095c6c9bdcc51b74f" }
move-core-types = { git = "https://github.com/young-rocks/move", rev = "4e8d09188f056bf7a5daba4095c6c9bdcc51b74f" }
move-vm-runtime = { git = "https://github.com/young-rocks/move", rev = "4e8d09188f056bf7a5daba4095c6c9bdcc51b74f" }
move-vm-types = { git = "https://github.com/young-rocks/move", rev = "4e8d09188f056bf7a5daba4095c6c9bdcc51b74f" }
logger = { path = "../common/logger" }
error = { path = "../common/error" }
halo2_proofs = { git = "https://github.com/young-rocks/halo2", rev = "e5c022414e62154b66b9fbef463912768c15556a" }
anyhow = "1.0.38"