[package]
name = "movelang"
version = "0.1.0"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]
edition = "2018"

[dependencies]
move-lang = { git = "https://github.com/zkmove/diem", rev ="85588fbcff7246d0d47daea7bae861a3b36bdb6b" }
move-binary-format = { git = "https://github.com/zkmove/diem", rev ="85588fbcff7246d0d47daea7bae861a3b36bdb6b" }
move-core-types = { git = "https://github.com/zkmove/diem", rev ="85588fbcff7246d0d47daea7bae861a3b36bdb6b" }
move-vm-runtime = { git = "https://github.com/zkmove/diem", rev ="85588fbcff7246d0d47daea7bae861a3b36bdb6b" }
move-vm-types = { git = "https://github.com/zkmove/diem", rev ="85588fbcff7246d0d47daea7bae861a3b36bdb6b" }
logger = { path = "../common/logger" }

anyhow = "1.0.38"