[package]
name = "crypto"
version = "0.1.0"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
bellman = { package = "bellman_ce", version = "0.3.5" }
#bellman = { package = "bellman", version = "0.10.0" }
